"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-04 00:00:00.000000

The chain previously began at ``20260905_01``, which is a *delta*: it issues
``ALTER TABLE users ADD COLUMN is_admin`` and ``ALTER TABLE chat_history ADD
COLUMN user_id``. Nothing in alembic had ever created ``users``, so running
``alembic upgrade head`` against an empty database died on the first statement:

    asyncpg.exceptions.UndefinedTableError: relation "users" does not exist
    [SQL: ALTER TABLE users ADD COLUMN is_admin BOOLEAN DEFAULT false NOT NULL]

The chain had no base revision -- only ``main.py``'s ``create_all`` ever built
the schema, which meant migrations could not reproduce a database from nothing
and a fresh deployment had no path through them at all.

This migration supplies the missing base. It creates exactly the three tables
``20260905_01`` assumes are already present, in the shape they had *before*
that revision ran:

* ``users``       -- without ``is_admin``, which ``20260905_01`` adds
* ``chat_history``-- without ``user_id``, which ``20260905_01`` adds
* ``bookings``    -- unchanged by the rest of the chain, and the target of the
  ``booking_events`` foreign keys created in ``20260905_01``

Deliberately *not* a full dump of today's models. A base revision has to
describe the schema as it was at that point in history; emitting the current
``Base.metadata`` here would make every subsequent migration fail on "table
already exists" and would rewrite history every time a model changed.

The revision id is deliberately short and opaque. `alembic_version.version_num`
is `VARCHAR(32)`, and a descriptive id like
`20260905_01_add_booking_events_and_admin_flag` (45 chars) cannot be written
there at all:

    asyncpg.exceptions.StringDataRightTruncationError:
      value too long for type character varying(32)

so `alembic upgrade` failed the moment it tried to record the revision. The
date and the description live in the filename and this docstring, where they
cost nothing; the id stays inside the column that has to hold it.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "chat_history",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        # No `user_id`: 20260905_01 adds that column, together with its foreign
        # key and index. Creating it here as well made that migration fail with
        # `column "user_id" of relation "chat_history" already exists`, so a base
        # revision has to stop exactly where the next one starts.
        sa.Column("message", sa.Text(), nullable=False),
        # NOT NULL, matching `models.ChatHistory.response`. The column is
        # declared nullable here only when the base and the model disagree, and
        # the disagreement shows up as an `alter_column` in the next
        # autogenerated revision -- so it is stated correctly here instead.
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(op.f("ix_chat_history_id"), "chat_history", ["id"], unique=False)

    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # Native enum types, matching `models.Booking`'s
        # `SAEnum(..., native_enum=True)`. Declaring these as VARCHAR and
        # converting them later produces a *different* database from the one
        # `create_all` makes: the column type, the type name, and whether the
        # database enforces the vocabulary all differ. A deployment that used
        # migrations and one that booted the app would then disagree about the
        # schema of the same table.
        #
        # The value lists are written out rather than imported from
        # `app.models` on purpose: a migration records what was true at that
        # point, so a later change to the model's enum is a new migration
        # rather than a silent rewrite of history. `scripts/schema_drift_report.py`
        # compares the result against the models, so a divergence here is
        # reported rather than silent.
        sa.Column(
            "service_type",
            sa.Enum(
                "consultation", "delivery", "meeting", "project", name="servicetype"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("details", sa.Text(), nullable=False, server_default=""),
        sa.Column("scheduled_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "cancelled", "completed", name="bookingstatus"
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scheduled_date IS NOT NULL", name="ck_bookings_scheduled_date_required"
        ),
    )
    op.create_index(op.f("ix_bookings_id"), "bookings", ["id"], unique=False)
    # Deliberately no `ix_bookings_user_id`: `models.Booking.user_id` declares
    # no index, so creating one here would produce a database the models do not
    # describe. (Every booking lookup is by user, which is the case *for* an
    # index -- but that is a schema change to make deliberately in the models,
    # not something a base migration should quietly introduce.)


def downgrade() -> None:
    op.drop_index(op.f("ix_bookings_id"), table_name="bookings")
    op.drop_table("bookings")

    op.drop_index(op.f("ix_chat_history_id"), table_name="chat_history")
    op.drop_table("chat_history")

    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")

    # Drop the two native enums this revision created.
    #
    # `DROP TABLE` takes the *columns* with it but leaves the type behind, so
    # without these the downgrade reports success and the next `upgrade head`
    # fails with `type "servicetype" already exists`. That made the round trip
    # look broken while leaving the database in a state where it was neither up
    # nor down: tables gone, types not, and the failure surfacing one command
    # later than the cause.
    #
    # `checkfirst=True` because SQLite has no standalone enum type to drop -- the
    # values live inline in the column definition -- so asking it to drop one
    # raises rather than no-ops.
    for type_name in ("bookingstatus", "servicetype"):
        sa.Enum(name=type_name).drop(op.get_bind(), checkfirst=True)
