"""sync remaining schema to models

Revision ID: 0007_sync_remaining_schema
Revises: 0006_complaints
Create Date: 2026-09-30 06:47:35.800933

Why this revision exists
------------------------
The chain built by hand so far covered twelve of the twenty-two tables. Ten
were never migrated at all, so `alembic upgrade head` produced a database the
application could not use -- while every migration-level test still passed,
because each one was verified against the *models* or against SQLite, and
nothing compared the chain's result against a real PostgreSQL database.

The gap was only visible once the chain was actually run end to end
(`scripts/schema_drift_report.py`):

    live tables    : 12
    declared tables: 22
    MISSING: arrears_entries, audit_log_entries, communication_overrides,
             customer_policy_scores, interaction_signals, points_transactions,
             points_wallets, recovery_actions, security_events,
             topic_selections
    COLUMN DRIFT chat_history:      missing created_at, updated_at
    COLUMN DRIFT booking_events:    missing updated_at
    COLUMN DRIFT recovery_outcomes: missing follow_up_json

Those four columns come from `TimestampMixin` and were absent from the
hand-written `create_table` calls that predate this revision.

Generated with `alembic revision --autogenerate` and then reviewed: `upgrade()`
is purely additive (no `drop_*`, no `alter_column`), and `downgrade()` reverses
exactly what `upgrade()` did. Body formatting is Alembic's, left as generated
rather than hand-reformatted, so the next autogenerate produces a reviewable
diff.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0007_sync_remaining_schema"
down_revision: Union[str, Sequence[str], None] = "0006_complaints"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrears_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=False),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('compounding', sa.String(length=20), nullable=False),
    sa.Column('interest_cap_pct', sa.Float(), nullable=False),
    sa.Column('defer_days', sa.Integer(), nullable=False),
    sa.Column('interest_accrued', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_interest', sa.Float(), nullable=False),
    sa.Column('total_settled', sa.Float(), nullable=False),
    sa.Column('interest_waived', sa.Boolean(), nullable=False),
    sa.Column('waived_interest', sa.Float(), nullable=False),
    sa.Column('late_fee_amount', sa.Float(), nullable=False),
    sa.Column('late_fee_pct', sa.Float(), nullable=False),
    sa.Column('late_fee_charged', sa.Boolean(), nullable=False),
    sa.Column('fees_waived', sa.Boolean(), nullable=False),
    sa.Column('waived_fees', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annual_rate >= 0', name='ck_arrears_entries_annual_rate_non_negative'),
    sa.CheckConstraint('principal >= 0', name='ck_arrears_entries_principal_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrears_entries_booking_id'), 'arrears_entries', ['booking_id'], unique=False)
    op.create_index(op.f('ix_arrears_entries_id'), 'arrears_entries', ['id'], unique=False)
    op.create_index(op.f('ix_arrears_entries_policy_id'), 'arrears_entries', ['policy_id'], unique=False)
    op.create_index(op.f('ix_arrears_entries_service_type'), 'arrears_entries', ['service_type'], unique=False)
    op.create_index(op.f('ix_arrears_entries_status'), 'arrears_entries', ['status'], unique=False)
    op.create_index(op.f('ix_arrears_entries_user_id'), 'arrears_entries', ['user_id'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('info','warning','critical')", name='ck_audit_log_entries_severity_valid'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_actor_user_id'), 'audit_log_entries', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_id'), 'audit_log_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_type'), 'audit_log_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_id'), 'audit_log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_severity'), 'audit_log_entries', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_source'), 'audit_log_entries', ['source'], unique=False)
    op.create_table('communication_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('set_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_overrides_id'), 'communication_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_communication_overrides_profile_id'), 'communication_overrides', ['profile_id'], unique=False)
    op.create_index(op.f('ix_communication_overrides_user_id'), 'communication_overrides', ['user_id'], unique=True)
    op.create_table('customer_policy_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_score', sa.Float(), nullable=False),
    sa.Column('customer_score', sa.Float(), nullable=False),
    sa.Column('access_score', sa.Float(), nullable=False),
    sa.Column('interest_score', sa.Float(), nullable=False),
    sa.Column('closeness_score', sa.Float(), nullable=False),
    sa.Column('community_closeness_score', sa.Float(), nullable=False),
    sa.Column('policy_tier', sa.String(length=20), nullable=False),
    sa.Column('control_posture', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('customer_score >= 0', name='ck_customer_policy_scores_customer_score_non_negative'),
    sa.CheckConstraint('system_score >= 0', name='ck_customer_policy_scores_system_score_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_policy_scores_control_posture'), 'customer_policy_scores', ['control_posture'], unique=False)
    op.create_index(op.f('ix_customer_policy_scores_id'), 'customer_policy_scores', ['id'], unique=False)
    op.create_index(op.f('ix_customer_policy_scores_policy_tier'), 'customer_policy_scores', ['policy_tier'], unique=False)
    op.create_index(op.f('ix_customer_policy_scores_user_id'), 'customer_policy_scores', ['user_id'], unique=True)
    op.create_table('interaction_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0', name='ck_interaction_signals_score_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_signals_area'), 'interaction_signals', ['area'], unique=False)
    op.create_index(op.f('ix_interaction_signals_id'), 'interaction_signals', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_signals_user_id'), 'interaction_signals', ['user_id'], unique=False)
    op.create_table('points_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_type', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('points_delta', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('currency_amount', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_transactions_id'), 'points_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_points_transactions_kind'), 'points_transactions', ['kind'], unique=False)
    op.create_index(op.f('ix_points_transactions_point_type'), 'points_transactions', ['point_type'], unique=False)
    op.create_index(op.f('ix_points_transactions_user_id'), 'points_transactions', ['user_id'], unique=False)
    op.create_table('points_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_type', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_points_wallets_balance_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'point_type', name='uq_points_wallets_user_type')
    )
    op.create_index(op.f('ix_points_wallets_id'), 'points_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_points_wallets_point_type'), 'points_wallets', ['point_type'], unique=False)
    op.create_index(op.f('ix_points_wallets_user_id'), 'points_wallets', ['user_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_action'), 'recovery_actions', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_actions_id'), 'recovery_actions', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_playbook_id'), 'recovery_actions', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_reference'), 'recovery_actions', ['reference'], unique=False)
    op.create_index(op.f('ix_recovery_actions_status'), 'recovery_actions', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_user_id'), 'recovery_actions', ['user_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_kind', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('partition_key', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_actor_user_id'), 'security_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_kind'), 'security_events', ['event_kind'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_index(op.f('ix_security_events_partition_key'), 'security_events', ['partition_key'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_tenant_id'), 'security_events', ['tenant_id'], unique=False)
    op.create_table('topic_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_selections_id'), 'topic_selections', ['id'], unique=False)
    op.create_index(op.f('ix_topic_selections_is_current'), 'topic_selections', ['is_current'], unique=False)
    op.create_index(op.f('ix_topic_selections_topic'), 'topic_selections', ['topic'], unique=False)
    op.create_index(op.f('ix_topic_selections_user_id'), 'topic_selections', ['user_id'], unique=False)
    op.add_column('booking_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_booking_events_id'), 'booking_events', ['id'], unique=False)
    op.add_column('chat_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('recovery_outcomes', sa.Column('follow_up_json', sa.Text(), nullable=False))
    op.create_index(op.f('ix_retention_snapshots_id'), 'retention_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_snapshots_id'), table_name='retention_snapshots')
    op.drop_column('recovery_outcomes', 'follow_up_json')
    op.drop_column('chat_history', 'updated_at')
    op.drop_column('chat_history', 'created_at')
    op.drop_index(op.f('ix_booking_events_id'), table_name='booking_events')
    op.drop_column('booking_events', 'updated_at')
    op.drop_index(op.f('ix_topic_selections_user_id'), table_name='topic_selections')
    op.drop_index(op.f('ix_topic_selections_topic'), table_name='topic_selections')
    op.drop_index(op.f('ix_topic_selections_is_current'), table_name='topic_selections')
    op.drop_index(op.f('ix_topic_selections_id'), table_name='topic_selections')
    op.drop_table('topic_selections')
    op.drop_index(op.f('ix_security_events_tenant_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_partition_key'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_kind'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_actor_user_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_recovery_actions_user_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_status'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_reference'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_playbook_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_action'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_points_wallets_user_id'), table_name='points_wallets')
    op.drop_index(op.f('ix_points_wallets_point_type'), table_name='points_wallets')
    op.drop_index(op.f('ix_points_wallets_id'), table_name='points_wallets')
    op.drop_table('points_wallets')
    op.drop_index(op.f('ix_points_transactions_user_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_point_type'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_kind'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_id'), table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_index(op.f('ix_interaction_signals_user_id'), table_name='interaction_signals')
    op.drop_index(op.f('ix_interaction_signals_id'), table_name='interaction_signals')
    op.drop_index(op.f('ix_interaction_signals_area'), table_name='interaction_signals')
    op.drop_table('interaction_signals')
    op.drop_index(op.f('ix_customer_policy_scores_user_id'), table_name='customer_policy_scores')
    op.drop_index(op.f('ix_customer_policy_scores_policy_tier'), table_name='customer_policy_scores')
    op.drop_index(op.f('ix_customer_policy_scores_id'), table_name='customer_policy_scores')
    op.drop_index(op.f('ix_customer_policy_scores_control_posture'), table_name='customer_policy_scores')
    op.drop_table('customer_policy_scores')
    op.drop_index(op.f('ix_communication_overrides_user_id'), table_name='communication_overrides')
    op.drop_index(op.f('ix_communication_overrides_profile_id'), table_name='communication_overrides')
    op.drop_index(op.f('ix_communication_overrides_id'), table_name='communication_overrides')
    op.drop_table('communication_overrides')
    op.drop_index(op.f('ix_audit_log_entries_source'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_severity'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_arrears_entries_user_id'), table_name='arrears_entries')
    op.drop_index(op.f('ix_arrears_entries_status'), table_name='arrears_entries')
    op.drop_index(op.f('ix_arrears_entries_service_type'), table_name='arrears_entries')
    op.drop_index(op.f('ix_arrears_entries_policy_id'), table_name='arrears_entries')
    op.drop_index(op.f('ix_arrears_entries_id'), table_name='arrears_entries')
    op.drop_index(op.f('ix_arrears_entries_booking_id'), table_name='arrears_entries')
    op.drop_table('arrears_entries')
    # ### end Alembic commands ###
