#!/usr/bin/env python3
"""Regenerate the backend code map in strict single-line Newick format.

Usage:
    python3 scripts/build_code_map.py            # rewrite CODE_MAP.newick
    python3 scripts/build_code_map.py --check     # validate without writing

The tree is defined below as nested tuples ``(label, *children)`` where a child
is either a leaf name (str) or another node tuple. Serialization is trivially
deterministic, so diffs stay readable. Never hand-edit ``CODE_MAP.newick``;
edit this script and re-run it (governance rule #4 in ``CODE_MAP.md``).
"""
from __future__ import annotations

from pathlib import Path
import sys
import argparse

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "CODE_MAP.newick"
HEADER = (
    "# CService Backend - Code Map (Newick)\n"
    "# Single-line Newick tree: leaves are business-logic surfaces, internal node\n"
    "# labels name layers/domains. Governance + revision log live in CODE_MAP.md.\n"
    "# Generated by scripts/build_code_map.py -- do not hand-edit.\n"
)


def _node(label: str, *children):
    return (label,) + tuple(children)


# ---------------------------------------------------------------------------
# The tree. Layers: infra, models, routers, services, schemas (root cservice_backend).
# ---------------------------------------------------------------------------

TREE = _node(
    "cservice_backend",
    _node(  # infra ----------------------------------------------------------
        "infra",
        _node(
            "main",
            "startup_lifespan", "cors", "exception_handler", "meta", "health",
            "runtime", "scoring_catalog", "i18n_endpoint", "features", "ecosystem",
            "tenants", "tenants_policy", "partitions", "zero_trust", "decisions",
            "regional_endpoint", "model_bases_endpoint", "policy_scoring_endpoint",
            "customer_360_endpoint",
        ),
        _node(
            "db",
            "engine", "pool_config", "session", "ping", "retry",
            "retry_policy", "retry_classification", "circuit_breaker",
            "statement_timeouts", "advisory_lock", "transaction",
            "pool_status", "db_health", "readiness_probe", "test_connection",
            "catalog",
        ),
        _node(
            "security",
            "verify_password", "hash_password", "access_token", "refresh_token",
            "decode_token", "password_policy",
            "key_rotation", "token_revocation", "token_validation",
            "step_up", "api_keys", "password_strength", "password_history",
            "catalog",
        ),
        _node(
            "auth_deps",
            "current_user", "optional_user", "admin_user", "policy_or_admin",
            "policy_score", "control_posture",
            "principal", "optional_principal", "require_principal",
            "correlation_id", "require_scopes", "require_roles",
            "require_step_up", "require_cell_access", "require_tenant",
            "rate_limit", "catalog",
            # Config-table driven authorization governance. The request path
            # is unchanged; these are the readers, the engine and the reports.
            "scope_catalog", "role_scope_grants", "denial_contract",
            "step_up_ranks", "rate_tiers", "route_rules", "public_write_exceptions",
            "decision_engine",
            "drift", "simulation", "validation", "authz_catalog",
            "rate_tier",
        ),
        _node("localization",
              "locale_resolution", "locale_payload", "message_catalog", "translate", "catalog_builder",
              "locale_normalization", "accept_language", "negotiation",
              "plural_rules", "fallback_chain", "coverage", "overrides",
              "translate_many",
              # Governance layer. The resolution and render path above is
              # unchanged; these are the tables, the readers and the reports.
              "namespaces", "placeholder_policies", "locale_expectations",
              "number_formats", "render_ops", "findings_taxonomy",
              "template_scan", "placeholder_audit", "budget_report",
              "unbalanced_templates", "plural_audit", "negotiation_audit",
              "locale_registry_audit", "format_number", "i18n_validation",
              "governance_catalog"),
        _node(  # Stage 1A: multi-tenant DB routing + partition lifecycle
            "multi_tenant",
            _node("tenant_router",
                  "registry", "route_for_tenant", "tenant_session", "declared_tenants", "catalog",
                  "tenant_validation", "request_resolution", "dsn_redaction",
                  "routing_policy", "tenant_health", "provisioning_plan"),
            _node("partition_manager",
                  "policies", "ensure_partition", "archive", "drop_expired", "worker", "catalog",
                  "identifier_validation", "period_keys", "sql_builders",
                  "policy_validation", "catalog_reads", "legal_holds",
                  "lifecycle_plan", "adopt_partitions", "attach_restore",
                  "dry_run"),
        ),
        _node(  # Stage 1B: cryptographic security & zero-trust access
            "zero_trust",
            _node("hsm_signer",
                  "hmac_signer", "ed25519_signer", "sign_bytes", "verify_bytes",
                  "signature_envelope", "catalog",
                  "backend_registry", "signing_key_ring", "key_fingerprint",
                  "detailed_verification", "co_signature", "multi_signature",
                  "replay_guard", "self_test", "health"),
            _node("biometric_vault",
                  "modalities", "register", "validate", "revoke", "list_templates", "catalog",
                  "adaptive_thresholds", "slot_enrollment", "challenges",
                  "attempt_lockout", "match_decision", "history",
                  "state_export", "state_import", "snapshot"),
            _node("risk_evaluator",
                  "risk_levels", "risk_rules", "evaluate", "adaptive_weights", "catalog",
                  "signal_normalization", "context_gaps", "required_controls",
                  "action_mapping", "counterfactuals", "weight_history",
                  "weight_versions", "outcome_batches", "risk_decisions"),
            _node("cell_matrix",
                  "access_levels", "cell_matrix", "evaluate", "resolve_roles", "catalog",
                  "row_scopes", "cell_overrides", "masking", "resource_plans",
                  "override_simulation", "temporary_grants"),
        ),
        _node(  # Stage 1C: high-velocity audit isolation
            "event_pipeline",
            _node("high_throughput_pipeline",
                  "workers", "batch", "submit", "drain", "dead_letter", "stats", "catalog",
                  "replay_policy", "replay_dead_letters"),
            _node("protobuf_transaction_spec",
                  "wire_format", "transaction", "hash_chain", "append_only_log", "spec_catalog",
                  "query", "integrity_report", "export"),
        ),
        _node(  # Phase 1: decision quality & consistency
            "decision_intelligence",
            _node("model_versioning",
                  "registry", "snapshots", "canary", "shadow_scoring", "promote", "catalog",
                  "lifecycle", "promotion_gates", "version_diff", "rollback_policy",
                  "deprecation", "prune", "traffic_split", "label_templates"),
            _node("simulation_engine",
                  "what_if", "risk_scenarios", "retention_scenarios", "reports", "catalog",
                  "scenario_library", "partition_policies", "sensitivity", "comparison"),
            _node("explainability",
                  "decision_trace", "trace_store", "explain", "factor_trail", "catalog",
                  "counterfactuals", "audiences", "replay", "regression"),
            _node("optimistic_locking",
                  "version_guard", "compare_and_swap", "stale_conflict", "conflict_policy",
                  "versioned_records", "versioned_store", "field_diffs",
                  "json_merge_patch", "retry_updates", "lock_sets",
                  "merge_semantics", "advisory_locks", "audit", "catalog"),
        ),
        _node(  # Kaizen: simulated real-life flows, the one-way shadow, and
            # the graded maturity ladder. Three modules, one surface: a kaizen
            # change is simulated, run against replicated data in an environment
            # that cannot reach live, and promoted one measured rung at a time.
            # Its own layer rather than leaves under `services` because the code
            # is about changes to the other code -- nothing here is a business
            # engine, and putting it beside the engines it simulates would make
            # the map say it was one.
            "kaizen",
            _node("flow_simulation",
                  "personas", "probes", "flow_catalog", "runs", "comparisons",
                  "blockage_classification", "blockage_report", "blockage_append",
                  "measurement", "validation", "catalog"),
            _node("shadow_env",
                  "environments", "feeds", "isolation_checks", "database_identity",
                  "direction_arithmetic", "replicated_field_audit", "leakage_paths",
                  "observations", "process_observations", "isolation_verdict",
                  "validation", "catalog"),
            _node("release_ladder",
                  "levels", "gates", "gate_evaluator", "candidates",
                  "candidate_registry", "ledger", "rollback_window", "rollback",
                  "safe_levels", "measurements", "validation", "catalog"),
        ),
        _node(  # Stage 1: business-rule hyper-flexibility
            "business_rules",
            _node("rule_engine",
                  "field_dsl", "combinators", "date_ops", "expressions", "catalog",
                  "operators", "policy", "validation", "explanation", "packs"),
            _node("regional_policy",
                  "calendars", "labor_rules", "tax_rules", "booking_assessment", "catalog",
                  "jurisdictions", "compliance", "holiday_resolution", "quotas"),
        ),
    ),
    _node(  # models -----------------------------------------------------------
        "models",
        _node("model_bases",
              "timestamp", "tenant_scoped", "partitioned", "security_event",
              "soft_delete", "row_version", "expiring", "actor_audit",
              "serialization", "security_event_extensions", "entity_registry",
              "catalog"),
        # The metadata layer: config tables + pure helpers over Base.metadata.
        # No DDL, so no migration -- the DDL layer above it is untouched.
        _node("metadata",
              "sensitivity_vocabulary", "redaction_presets", "json_payloads",
              "enum_vocabulary", "table_lifecycle",
              "introspection", "enum_access", "serialization",
              "constraint_coverage", "referential_gaps",
              "relationship_catalog", "schema_catalog"),
        "user", "booking", "booking_event", "booking_assignment", "chat_history",
        "interaction_signal", "retention_snapshot", "recovery_outcome", "recovery_action",
        "customer_policy_score", "topic_selection", "communication_override",
        "arrears_entry", "points_wallet", "points_transaction", "audit_log_entry",
        # Stage A: the preference centre stores current state in a mutable
        # singleton and the consent trail beside it in append-only rows, so a
        # revocation stays provable after the profile row is overwritten.
        "user_preference_profile", "user_consent_event",
    ),
    _node(  # routers ----------------------------------------------------------
        "routers",
        _node("users",
              "register", "login", "me", "policy_score", "can_access",
              "policy_decision", "change_password",
              "session_refresh", "logout", "session_inventory",
              "step_up", "api_keys", "password_policy",
              "password_feedback", "security_posture", "catalog"),
        _node("bookings",
              "lifecycle_crud", "analytics", "assignment_report", "audit_history", "export"),
        _node("chat",
              "history", "sentiment", "insights", "recovery", "recovery_playbooks",
              "loyalty_journey",
              "retention_dashboard", "snapshot_operations", "activity_tree",
              "communication_strategy", "arrears_payments", "points_exchange", "topic_policy",
              # Stage A, as four business surfaces rather than eleven routes:
              # maintenance rule 3 forbids enumerating endpoints as leaves.
              "customer_360", "self_service", "customer_explanations",
              "preference_consent"),
        _node("topics",
              "catalog", "themes", "intelligence", "coverage", "portfolio", "workspace",
              "overview", "search", "suggestions", "recommendations",
              "current_selection", "history",
              # governance block in services/topics.py; the new routes are
              # pre-flight / advisory and never mutate a selection
              "taxonomy", "governance", "integrity", "match", "ranked",
              "validate", "drift", "lifecycle"),
        # Complaints. Its own router rather than leaves under `chat`, because a
        # case has an identity that outlives the session that produced it and is
        # quoted over the phone days later -- treating it as a chat message is
        # what made the previous surface untrackable. Grouped into business
        # surfaces per maintenance rule 3, not one leaf per route.
        _node("complaints",
              "case", "case_list", "case_detail", "note", "withdraw", "reopen",
              "acknowledge", "resolve", "close",
              "decision_support", "apply", "customer_visibility",
              "queue", "sla_report", "auto_escalation_sweep", "decision_audit",
              "governance"),
        # The release surface. Its own router node rather than leaves under
        # `main`: every other node here is a business surface a customer or an
        # operator uses, and this one is the set of acts that change what the
        # others do -- simulation, verification, promotion, rollback. Grouped
        # into business surfaces per maintenance rule 3, not one leaf per route.
        _node("kaizen",
              "catalog", "flow_catalog", "flow_simulation", "flow_sweep",
              "blockage_report", "blockage_log",
              "shadow_report", "shadow_verification",
              "maturity_levels", "candidate_registry", "candidate_measurement",
              "promotion", "safe_levels", "deployment_ledger", "rollback"),
        _node("audit",
              "efficiency", "enhancements", "audit_catalog", "trail_catalog", "log",
              "logs", "summary", "pipeline_stats", "pipeline_event", "transactions",
              "protobuf_spec",
              "governed_log", "integrity", "actors", "timeline",
              "anomalies", "retention", "export",
              "view", "integrity_gates", "dead_letters", "replay",
              "transactions_query", "transactions_integrity", "transactions_export"),
    ),
    _node(  # services ---------------------------------------------------------
        "services",
        _node("chat_analytics",
              "area_scoring", "sentiment", "insights", "recovery", "topic_ranking",
              "topic_policy", "capabilities"),
        _node("topics",
              "catalog", "search", "suggestion", "theme", "selection", "workspace",
              "intelligence", "coverage"),
        _node("bookings",
              "lifecycle", "normalization", "transitions", "ownership", "assignment_report"),
        _node("policy_scoring",
              "policy_tier", "control_posture", "access_band", "can_access", "decision_reports",
              "composition", "topic_metrics", "posture_adjustment", "tier_escalation",
              "health", "recommendations", "decision_trace", "what_if", "coverage",
              "validation", "ops_catalog"),
        _node("retention",
              "snapshots", "trends", "deltas", "retention_dashboard"),
        _node("retention_snapshot_ops",
              "freshness", "health", "operations_status", "compliance", "posture",
              "automation", "launch_readiness", "go_no_go"),
        _node("loyalty_journey",
              "scenario_catalog", "matching", "journey_plan", "admin_report"),
        _node("activity_tree",
              "grouping", "ranking", "smart_filter", "anomaly_rules", "admin_trees"),
        _node("communication_strategy",
              "override", "policy", "culture", "profile", "mood", "decision_trail"),
        _node("efficiency_audit",
              "component_scoring", "classifications", "enhancement_proposals", "catalog"),
        _node("arrears_payments",
              "interest_policies", "late_fees", "quote", "open", "settle",
              "waive_interest", "waive_fees", "waiver_policy"),
        _node("points_exchange",
              "rate_rules", "rate_multipliers", "campaigns", "quote", "wallet",
              "ledger", "admin_rollup"),
        _node("recovery_playbooks",
              "realtime_context", "playbook_rules", "credit_points", "escalation",
              "policy_guardrail", "orchestrator", "auto_sweep", "catalog"),
        # Stage A (Trust & Visibility). Four services, one per sub-surface; the
        # aggregator is leaf-level under its own node because its sections are
        # composable individually via the `section=` query parameter.
        _node("customer_360",
              "profile", "interactions", "sentiment", "recovery", "loyalty_journey",
              "communication", "payments", "points", "preferences", "admin_rollup"),
        _node("customer_explain",
              "score_bands", "friction_bands", "phrases", "recovery_narration",
              "next_steps", "loyalty_explanation", "churn_explanation",
              "recovery_explanation", "posture_explanation", "validation",
              "catalog"),
        _node("preferences",
              "catalog", "consents", "consent_trail", "consent_gate",
              "contact_window", "frequency", "channel_preference", "contact_plan",
              "update", "report"),
        _node("self_service",
              "recovery_status", "points_forecast", "policy_posture",
              "status_dashboard", "visible_actions"),
        # Complaints. One leaf per decision-support surface rather than per
        # config table, so the tree says what an operator can ask for.
        _node("complaints",
              "case_lifecycle", "case_timeline", "case_ownership",
              "escalation_triggers", "escalation_guards", "escalation_decision",
              "authority_floor", "routing", "sla_matrix", "regulatory_deadline",
              "decision_feeds", "decision_dossier", "precedent_retrieval",
              "decision_history", "auto_escalation_sweep", "sla_report",
              "admin_rollup", "case_linkage", "validation", "catalog"),
        _node("audit_log",
              "record", "list", "summary", "action_catalog",
              "governed_record", "action_aliases", "action_specs",
              "severity_policy", "justification", "sensitive_detail",
              "redaction", "change_detail", "paging", "count",
              "retention_plan", "retention_advice", "actor_activity",
              "entity_timeline", "anomaly_detection", "seal_chain",
              "chain_verification", "trail_export",
              "view_profiles", "integrity_gates", "entry_seal_chain", "catalog"),
    ),
    _node(  # schemas ----------------------------------------------------------
        "schemas",
        _node("schemas_core",
              "user", "token", "booking", "policy_score", "topic_selection",
              "session_lifecycle", "machine_credentials", "password_feedback",
              "security_posture", "step_up"),
        _node("schemas_chat",
              "insight", "recovery", "recovery_playbooks", "retention", "snapshot_ops", "topic_ranking", "topic_policy",
              # Stage A contract families, one leaf per payload family.
              "customer_360", "customer_explanations", "customer_recovery",
              "preference_consent", "self_service",
              # Complaints contract family.
              "complaint_case", "complaint_event", "complaint_decision",
              "complaint_dossier", "complaint_precedent",
              "complaint_decision_support", "complaint_admin", "complaint_catalog"),
        _node("schemas_audit",
              "efficiency", "enhancements", "audit_trail",
              "governed_write", "integrity", "actors", "timeline",
              "anomalies", "retention", "export",
              "view_projection", "integrity_gates", "dead_letters", "replay",
              "transaction_query", "transaction_integrity", "transaction_export",
              # Contract-governance layer over the 40 shipped models. The
              # contracts above are unchanged; these are the tables, the
              # readers and the reports.
              "kinds", "audiences", "field_policies", "trivial_fields",
              "forbidden_fields", "inventory", "write_paths", "contract_ops",
              "findings_taxonomy",
              "model_scan", "field_facts", "source_scan", "field_resolution",
              "route_map", "kind_inference",
              "contract_inventory", "field_description", "divergence_report",
              "redaction_report", "contract_validation", "governance_catalog"),
    ),
)


# ---------------------------------------------------------------------------
# Serialization + validation
# ---------------------------------------------------------------------------


def serialize(node) -> str:
    if isinstance(node, str):
        return node
    label = node[0]
    children = node[1:]
    return "(" + ",".join(serialize(child) for child in children) + ")" + label


class _Parser:
    def __init__(self, text: str):
        self.text = text
        self.pos = 0
        self.leaves = 0
        self.internal = 0

    def _label(self):
        start = self.pos
        while self.pos < len(self.text) and self.text[self.pos] not in "(),;":
            self.pos += 1
        return self.text[start:self.pos]

    def parse(self):
        self._skip_ws()
        if self.pos >= len(self.text) or self.text[self.pos] != "(":
            raise ValueError("tree must start with '('")
        self.node()
        self._skip_ws()
        if self.text[self.pos : self.pos + 1] != ";":
            raise ValueError("tree must end with ';'")

    def _skip_ws(self):
        while self.pos < len(self.text) and self.text[self.pos].isspace():
            self.pos += 1

    def node(self):
        assert self.text[self.pos] == "("
        self.pos += 1
        self._skip_ws()
        while True:
            if self.text[self.pos] == "(":
                self.node()
            else:
                label = self._label()
                if not label:
                    raise ValueError(f"empty leaf at offset {self.pos}")
                self.leaves += 1
            self._skip_ws()
            if self.text[self.pos] == ",":
                self.pos += 1
                self._skip_ws()
                continue
            if self.text[self.pos] == ")":
                self.pos += 1
                self._skip_ws()
                label = self._label()
                if not label:
                    raise ValueError("internal node missing label")
                self.internal += 1
                return
            raise ValueError(f"unexpected char {self.text[self.pos]!r} at offset {self.pos}")


def parse_and_count(text: str) -> tuple[int, int]:
    parser = _Parser(text)
    parser.parse()
    return parser.leaves, parser.internal


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="validate without writing")
    args = ap.parse_args()

    tree = serialize(TREE) + ";"
    leaves, internal = parse_and_count(tree)
    lines = HEADER + tree + "\n"
    print(f"leaves={leaves} internal_nodes={internal}")
    if args.check:
        return 0
    OUTPUT.write_text(lines, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())