#!/usr/bin/env python3
"""Regenerate the backend code map in strict single-line Newick format.

Usage:
    python3 scripts/build_code_map.py            # rewrite CODE_MAP.newick
    python3 scripts/build_code_map.py --check     # validate without writing

The tree is defined below as nested tuples ``(label, *children)`` where a child
is either a leaf name (str) or another node tuple. Serialization is trivially
deterministic, so diffs stay readable. Never hand-edit ``CODE_MAP.newick``;
edit this script and re-run it (governance rule #4 in ``CODE_MAP.md``).
"""
from __future__ import annotations

from pathlib import Path
import sys
import argparse

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "CODE_MAP.newick"
HEADER = (
    "# CService Backend - Code Map (Newick)\n"
    "# Single-line Newick tree: leaves are business-logic surfaces, internal node\n"
    "# labels name layers/domains. Governance + revision log live in CODE_MAP.md.\n"
    "# Generated by scripts/build_code_map.py -- do not hand-edit.\n"
)


def _node(label: str, *children):
    return (label,) + tuple(children)


# ---------------------------------------------------------------------------
# The tree. Layers: infra, models, routers, services, schemas (root cservice_backend).
# ---------------------------------------------------------------------------

TREE = _node(
    "cservice_backend",
    _node(  # infra ----------------------------------------------------------
        "infra",
        _node(
            "main",
            "startup_lifespan", "cors", "exception_handler", "meta", "health",
            "runtime", "scoring_catalog", "i18n_endpoint", "features", "ecosystem",
            "tenants", "partitions", "zero_trust",
        ),
        _node(
            "db",
            "engine", "pool_config", "session", "ping", "retry",
        ),
        _node(
            "security",
            "verify_password", "hash_password", "access_token", "refresh_token",
            "decode_token", "password_policy",
        ),
        _node(
            "auth_deps",
            "current_user", "optional_user", "admin_user", "policy_or_admin",
            "policy_score", "control_posture",
        ),
        _node("localization",
              "locale_resolution", "locale_payload", "message_catalog", "translate", "catalog_builder"),
        _node(  # Stage 1A: multi-tenant DB routing + partition lifecycle
            "multi_tenant",
            _node("tenant_router",
                  "registry", "route_for_tenant", "tenant_session", "declared_tenants", "catalog"),
            _node("partition_manager",
                  "policies", "ensure_partition", "archive", "drop_expired", "worker", "catalog"),
        ),
        _node(  # Stage 1B: cryptographic security & zero-trust access
            "zero_trust",
            _node("hsm_signer",
                  "hmac_signer", "ed25519_signer", "sign_bytes", "verify_bytes",
                  "signature_envelope", "catalog"),
            _node("biometric_vault",
                  "modalities", "register", "validate", "revoke", "list_templates", "catalog"),
            _node("risk_evaluator",
                  "risk_levels", "risk_rules", "evaluate", "adaptive_weights", "catalog"),
            _node("cell_matrix",
                  "access_levels", "cell_matrix", "evaluate", "resolve_roles", "catalog"),
        ),
        _node(  # Stage 1C: high-velocity audit isolation
            "event_pipeline",
            _node("high_throughput_pipeline",
                  "workers", "batch", "submit", "drain", "dead_letter", "stats", "catalog"),
            _node("protobuf_transaction_spec",
                  "wire_format", "transaction", "hash_chain", "append_only_log", "spec_catalog"),
        ),
    ),
    _node(  # models -----------------------------------------------------------
        "models",
        _node("model_bases",
              "timestamp", "tenant_scoped", "partitioned", "security_event"),
        "user", "booking", "booking_event", "booking_assignment", "chat_history",
        "interaction_signal", "retention_snapshot", "recovery_outcome",
        "customer_policy_score", "topic_selection", "communication_override",
        "arrears_entry", "points_wallet", "points_transaction", "audit_log_entry",
    ),
    _node(  # routers ----------------------------------------------------------
        "routers",
        _node("users",
              "register", "login", "me", "policy_score", "can_access",
              "policy_decision", "change_password"),
        _node("bookings",
              "lifecycle_crud", "analytics", "assignment_report", "audit_history", "export"),
        _node("chat",
              "history", "sentiment", "insights", "recovery", "loyalty_journey",
              "retention_dashboard", "snapshot_operations", "activity_tree",
              "communication_strategy", "arrears_payments", "points_exchange", "topic_policy"),
        _node("topics",
              "catalog", "themes", "intelligence", "coverage", "portfolio", "workspace",
              "overview", "search", "suggestions", "recommendations",
              "current_selection", "history"),
        _node("audit",
              "efficiency", "enhancements", "audit_catalog", "trail_catalog", "log",
              "logs", "summary", "pipeline_stats", "pipeline_event", "transactions",
              "protobuf_spec"),
    ),
    _node(  # services ---------------------------------------------------------
        "services",
        _node("chat_analytics",
              "area_scoring", "sentiment", "insights", "recovery", "topic_ranking",
              "topic_policy", "capabilities"),
        _node("topics",
              "catalog", "search", "suggestion", "theme", "selection", "workspace",
              "intelligence", "coverage"),
        _node("bookings",
              "lifecycle", "normalization", "transitions", "ownership", "assignment_report"),
        _node("policy_scoring",
              "policy_tier", "control_posture", "access_band", "can_access", "decision_reports"),
        _node("retention",
              "snapshots", "trends", "deltas", "retention_dashboard"),
        _node("retention_snapshot_ops",
              "freshness", "health", "operations_status", "compliance", "posture",
              "automation", "launch_readiness", "go_no_go"),
        _node("loyalty_journey",
              "scenario_catalog", "matching", "journey_plan", "admin_report"),
        _node("activity_tree",
              "grouping", "ranking", "smart_filter", "anomaly_rules", "admin_trees"),
        _node("communication_strategy",
              "override", "policy", "culture", "profile", "mood", "decision_trail"),
        _node("efficiency_audit",
              "component_scoring", "classifications", "enhancement_proposals", "catalog"),
        _node("arrears_payments",
              "interest_policies", "quote", "open", "settle", "waive_interest"),
        _node("points_exchange",
              "rate_rules", "quote", "wallet", "ledger", "admin_rollup"),
        _node("audit_log",
              "record", "list", "summary", "action_catalog"),
    ),
    _node(  # schemas ----------------------------------------------------------
        "schemas",
        _node("schemas_core",
              "user", "token", "booking", "policy_score", "topic_selection"),
        _node("schemas_chat",
              "insight", "recovery", "retention", "snapshot_ops", "topic_ranking", "topic_policy"),
        _node("schemas_audit",
              "efficiency", "enhancements", "audit_trail"),
    ),
)


# ---------------------------------------------------------------------------
# Serialization + validation
# ---------------------------------------------------------------------------


def serialize(node) -> str:
    if isinstance(node, str):
        return node
    label = node[0]
    children = node[1:]
    return "(" + ",".join(serialize(child) for child in children) + ")" + label


class _Parser:
    def __init__(self, text: str):
        self.text = text
        self.pos = 0
        self.leaves = 0
        self.internal = 0

    def _label(self):
        start = self.pos
        while self.pos < len(self.text) and self.text[self.pos] not in "(),;":
            self.pos += 1
        return self.text[start:self.pos]

    def parse(self):
        self._skip_ws()
        if self.pos >= len(self.text) or self.text[self.pos] != "(":
            raise ValueError("tree must start with '('")
        self.node()
        self._skip_ws()
        if self.text[self.pos : self.pos + 1] != ";":
            raise ValueError("tree must end with ';'")

    def _skip_ws(self):
        while self.pos < len(self.text) and self.text[self.pos].isspace():
            self.pos += 1

    def node(self):
        assert self.text[self.pos] == "("
        self.pos += 1
        self._skip_ws()
        while True:
            if self.text[self.pos] == "(":
                self.node()
            else:
                label = self._label()
                if not label:
                    raise ValueError(f"empty leaf at offset {self.pos}")
                self.leaves += 1
            self._skip_ws()
            if self.text[self.pos] == ",":
                self.pos += 1
                self._skip_ws()
                continue
            if self.text[self.pos] == ")":
                self.pos += 1
                self._skip_ws()
                label = self._label()
                if not label:
                    raise ValueError("internal node missing label")
                self.internal += 1
                return
            raise ValueError(f"unexpected char {self.text[self.pos]!r} at offset {self.pos}")


def parse_and_count(text: str) -> tuple[int, int]:
    parser = _Parser(text)
    parser.parse()
    return parser.leaves, parser.internal


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="validate without writing")
    args = ap.parse_args()

    tree = serialize(TREE) + ";"
    leaves, internal = parse_and_count(tree)
    lines = HEADER + tree + "\n"
    print(f"leaves={leaves} internal_nodes={internal}")
    if args.check:
        return 0
    OUTPUT.write_text(lines, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())