#!/usr/bin/env python3
"""Regenerate the backend code map in strict single-line Newick format.

Usage:
    python3 scripts/build_code_map.py            # rewrite CODE_MAP.newick
    python3 scripts/build_code_map.py --check     # validate without writing

The tree is defined below as nested tuples ``(label, *children)`` where a child
is either a leaf name (str) or another node tuple. Serialization is trivially
deterministic, so diffs stay readable. Never hand-edit ``CODE_MAP.newick``;
edit this script and re-run it (governance rule #4 in ``CODE_MAP.md``).
"""
from __future__ import annotations

from pathlib import Path
import sys
import argparse

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "CODE_MAP.newick"
HEADER = (
    "# CService Backend - Code Map (Newick)\n"
    "# Single-line Newick tree: leaves are business-logic surfaces, internal node\n"
    "# labels name layers/domains. Governance + revision log live in CODE_MAP.md.\n"
    "# Generated by scripts/build_code_map.py -- do not hand-edit.\n"
)


def _node(label: str, *children):
    return (label,) + tuple(children)


# ---------------------------------------------------------------------------
# The tree. Layers: infra, models, routers, services, schemas (root cservice_backend).
# ---------------------------------------------------------------------------

TREE = _node(
    "cservice_backend",
    _node(  # infra ----------------------------------------------------------
        "infra",
        _node(
            "main",
            "startup_lifespan", "cors", "exception_handler", "meta", "health",
            "runtime", "scoring_catalog", "i18n_endpoint", "features", "ecosystem",
            "tenants", "tenants_policy", "partitions", "zero_trust", "decisions",
            "regional_endpoint", "model_bases_endpoint", "policy_scoring_endpoint",
            "customer_360_endpoint",
        ),
        _node(
            "db",
            "engine", "pool_config", "session", "ping", "retry",
            "retry_policy", "retry_classification", "circuit_breaker",
            "statement_timeouts", "advisory_lock", "transaction",
            "pool_status", "db_health", "readiness_probe", "test_connection",
            "catalog",
        ),
        _node(
            "security",
            "verify_password", "hash_password", "access_token", "refresh_token",
            "decode_token", "password_policy",
            "key_rotation", "token_revocation", "token_validation",
            "step_up", "api_keys", "password_strength", "password_history",
            "catalog",
        ),
        _node(
            "auth_deps",
            "current_user", "optional_user", "admin_user", "policy_or_admin",
            "policy_score", "control_posture",
            "principal", "optional_principal", "require_principal",
            "correlation_id", "require_scopes", "require_roles",
            "require_step_up", "require_cell_access", "require_tenant",
            "rate_limit", "public_rate_limit", "catalog",
            # Config-table driven authorization governance. The request path
            # is unchanged; these are the readers, the engine and the reports.
            "scope_catalog", "role_scope_grants", "denial_contract",
            "step_up_ranks", "rate_tiers", "route_rules", "public_write_exceptions",
            "decision_engine",
            "drift", "simulation", "validation", "authz_catalog",
            "rate_tier",
        ),
        _node("localization",
              "locale_resolution", "locale_payload", "message_catalog", "translate", "catalog_builder",
              "locale_normalization", "accept_language", "negotiation",
              "plural_rules", "fallback_chain", "coverage", "overrides",
              "translate_many",
              # Governance layer. The resolution and render path above is
              # unchanged; these are the tables, the readers and the reports.
              "namespaces", "placeholder_policies", "locale_expectations",
              "number_formats", "render_ops", "findings_taxonomy",
              "template_scan", "placeholder_audit", "budget_report",
              "unbalanced_templates", "plural_audit", "negotiation_audit",
              "locale_registry_audit", "format_number", "i18n_validation",
              "governance_catalog"),
        _node(  # Stage 1A: multi-tenant DB routing + partition lifecycle
            "multi_tenant",
            _node("tenant_router",
                  "registry", "route_for_tenant", "tenant_session", "declared_tenants", "catalog",
                  "tenant_validation", "request_resolution", "dsn_redaction",
                  "routing_policy", "tenant_health", "provisioning_plan"),
            _node("partition_manager",
                  "policies", "ensure_partition", "archive", "drop_expired", "worker", "catalog",
                  "identifier_validation", "period_keys", "sql_builders",
                  "policy_validation", "catalog_reads", "legal_holds",
                  "lifecycle_plan", "adopt_partitions", "attach_restore",
                  "dry_run"),
        ),
        _node(  # Stage 1B: cryptographic security & zero-trust access
            "zero_trust",
            _node("hsm_signer",
                  "hmac_signer", "ed25519_signer", "sign_bytes", "verify_bytes",
                  "signature_envelope", "catalog",
                  "backend_registry", "signing_key_ring", "key_fingerprint",
                  "detailed_verification", "co_signature", "multi_signature",
                  "replay_guard", "self_test", "health"),
            _node("biometric_vault",
                  "modalities", "register", "validate", "revoke", "list_templates", "catalog",
                  "adaptive_thresholds", "slot_enrollment", "challenges",
                  "attempt_lockout", "match_decision", "history",
                  "state_export", "state_import", "snapshot"),
            _node("risk_evaluator",
                  "risk_levels", "risk_rules", "evaluate", "adaptive_weights", "catalog",
                  "signal_normalization", "context_gaps", "required_controls",
                  "action_mapping", "counterfactuals", "weight_history",
                  "weight_versions", "outcome_batches", "risk_decisions"),
            _node("cell_matrix",
                  "access_levels", "cell_matrix", "evaluate", "resolve_roles", "catalog",
                  "row_scopes", "cell_overrides", "masking", "resource_plans",
                  "override_simulation", "temporary_grants"),
        ),
        _node(  # Stage 1C: high-velocity audit isolation
            "event_pipeline",
            _node("high_throughput_pipeline",
                  "workers", "batch", "submit", "drain", "dead_letter", "stats", "catalog",
                  "replay_policy", "replay_dead_letters"),
            _node("protobuf_transaction_spec",
                  "wire_format", "transaction", "hash_chain", "append_only_log", "spec_catalog",
                  "query", "integrity_report", "export"),
        ),
        _node(  # Phase 1: decision quality & consistency
            "decision_intelligence",
            _node("model_versioning",
                  "registry", "snapshots", "canary", "shadow_scoring", "promote", "catalog",
                  "lifecycle", "promotion_gates", "version_diff", "rollback_policy",
                  "deprecation", "prune", "traffic_split", "label_templates"),
            _node("simulation_engine",
                  "what_if", "risk_scenarios", "retention_scenarios", "reports", "catalog",
                  "scenario_library", "partition_policies", "sensitivity", "comparison"),
            _node("explainability",
                  "decision_trace", "trace_store", "explain", "factor_trail", "catalog",
                  "counterfactuals", "audiences", "replay", "regression"),
            _node("optimistic_locking",
                  "version_guard", "compare_and_swap", "stale_conflict", "conflict_policy",
                  "versioned_records", "versioned_store", "field_diffs",
                  "json_merge_patch", "retry_updates", "lock_sets",
                  "merge_semantics", "advisory_locks", "audit", "catalog"),
        ),
        _node(  # Kaizen: simulated real-life flows, the one-way shadow, and
            # the graded maturity ladder. Three modules, one surface: a kaizen
            # change is simulated, run against replicated data in an environment
            # that cannot reach live, and promoted one measured rung at a time.
            # Its own layer rather than leaves under `services` because the code
            # is about changes to the other code -- nothing here is a business
            # engine, and putting it beside the engines it simulates would make
            # the map say it was one.
            "kaizen",
            _node("flow_simulation",
                  "personas", "probes", "flow_catalog", "runs", "comparisons",
                  "blockage_classification", "blockage_report", "blockage_append",
                  "measurement", "validation", "catalog"),
            _node("shadow_env",
                  "environments", "feeds", "isolation_checks", "database_identity",
                  "direction_arithmetic", "replicated_field_audit", "leakage_paths",
                  "observations", "process_observations", "isolation_verdict",
                  "validation", "catalog"),
            _node("release_ladder",
                  "levels", "gates", "gate_evaluator", "candidates",
                  "candidate_registry", "ledger", "rollback_window", "rollback",
                  "safe_levels", "measurements", "validation", "catalog"),
            # The other axis to the simulation: not "does it behave" but "is it
            # there". Six graded states rather than a boolean, because a gap, a
            # defect and a part nobody has tested want different responses -- and
            # an immature backend is the starting state, so what counts as fatal
            # depends on the maturity rung being entered.
            _node("capability_audit",
                  "states", "inventory", "engine_resolution", "surface_resolution",
                  "stub_detector", "blind_probes", "orphan_probes",
                  "deferral", "level_measurements", "validation", "catalog"),
            # One entry point for all three subsystems, plus the timer. The CLI
            # and the background worker call the same function, so a check that
            # only runs when somebody remembers it cannot hide.
            _node("kaizen_sweep",
                  "run_sweep", "sections", "summarize", "exit_code",
                  "result_store", "sweep_history", "autostatus", "worker",
                  "async_sweep", "json"),
        ),
        _node(  # Stage 1: business-rule hyper-flexibility
            "business_rules",
            _node("rule_engine",
                  "field_dsl", "combinators", "date_ops", "expressions", "catalog",
                  "operators", "policy", "validation", "explanation", "packs"),
            _node("regional_policy",
                  "calendars", "labor_rules", "tax_rules", "booking_assessment", "catalog",
                  "jurisdictions", "compliance", "holiday_resolution", "quotas"),
        ),
    ),
    _node(  # models -----------------------------------------------------------
        "models",
        _node("model_bases",
              "timestamp", "tenant_scoped", "partitioned", "security_event",
              "soft_delete", "row_version", "expiring", "actor_audit",
              "serialization", "security_event_extensions", "entity_registry",
              "catalog"),
        # The metadata layer: config tables + pure helpers over Base.metadata.
        # No DDL, so no migration -- the DDL layer above it is untouched.
        _node("metadata",
              "sensitivity_vocabulary", "redaction_presets", "json_payloads",
              "enum_vocabulary", "table_lifecycle",
              "introspection", "enum_access", "serialization",
              "constraint_coverage", "referential_gaps",
              "relationship_catalog", "schema_catalog"),
        "user", "booking", "booking_event", "booking_assignment", "chat_history",
        "interaction_signal", "retention_snapshot", "recovery_outcome", "recovery_action",
        "customer_policy_score", "topic_selection", "communication_override",
        "arrears_entry", "points_wallet", "points_transaction", "audit_log_entry",
        # Stage A: the preference centre stores current state in a mutable
        # singleton and the consent trail beside it in append-only rows, so a
        # revocation stays provable after the profile row is overwritten.
        "user_preference_profile", "user_consent_event",
        # Sign-in: a device is recognised from digests rather than values, a
        # challenge is a rate-limited one-time code, an identity is an opt-in
        # identifier added unverified, and a storage connection holds encrypted
        # tokens. Grouped as four because each is a distinct durability story.
        "auth_device", "auth_challenge", "user_identity", "storage_connection",
    ),
    _node(  # routers ----------------------------------------------------------
        "routers",
        _node("users",
              "register", "login", "me", "policy_score", "can_access",
              "policy_decision", "change_password",
              "session_refresh", "logout", "session_inventory",
              "step_up", "api_keys", "password_policy",
              "password_feedback", "security_posture", "catalog"),
        # The sign-in surface is its own router even though every path is
        # mounted under /users: methods, recognition, trusted devices, linked
        # identities and storage are separately governed (four of its routes are
        # public writes in the authz audit), and folding them into the `users`
        # node would hide that. Grouped as four business surfaces rather than
        # fourteen routes, per maintenance rule 3.
        _node("identity",
              "sign_in_methods", "device_recognition_report",
              "trusted_devices", "linked_identities", "storage_connections"),
        _node("bookings",
              "lifecycle_crud", "analytics", "assignment_report", "audit_history", "export"),
        _node("chat",
              "history", "sentiment", "insights", "recovery", "recovery_playbooks",
              "loyalty_journey",
              "retention_dashboard", "snapshot_operations", "activity_tree",
              "communication_strategy", "arrears_payments", "points_exchange", "topic_policy",
              # Stage A, as four business surfaces rather than eleven routes:
              # maintenance rule 3 forbids enumerating endpoints as leaves.
              "customer_360", "self_service", "customer_explanations",
              "preference_consent"),
        _node("topics",
              "catalog", "themes", "intelligence", "coverage", "portfolio", "workspace",
              "overview", "search", "suggestions", "recommendations",
              "current_selection", "history",
              # governance block in services/topics.py; the new routes are
              # pre-flight / advisory and never mutate a selection
              "taxonomy", "governance", "integrity", "match", "ranked",
              "validate", "drift", "lifecycle"),
        # Complaints. Its own router rather than leaves under `chat`, because a
        # case has an identity that outlives the session that produced it and is
        # quoted over the phone days later -- treating it as a chat message is
        # what made the previous surface untrackable. Grouped into business
        # surfaces per maintenance rule 3, not one leaf per route.
        _node("complaints",
              "case", "case_list", "case_detail", "note", "withdraw", "reopen",
              "acknowledge", "resolve", "close",
              "decision_support", "apply", "customer_visibility",
              "queue", "sla_report", "auto_escalation_sweep", "decision_audit",
              "governance",
              # Complaint learning, under the complaints router because these
              # are `/complaints/admin/learning/*` and share the
              # `complaints_admin` authz rule. Grouped by surface rather than one
              # leaf per endpoint: the read half (catalog, weights, detect,
              # clusters, system-raised, blockages) and the write half (observe,
              # raise, proposals, publish) are two different risk profiles and
              # the split is the thing worth being able to see.
              "learning_catalog", "learning_weights", "learning_observe",
              "learning_detect", "learning_raise", "learning_system_raised",
              "learning_clusters", "learning_proposals", "learning_publish",
              "learning_blockages"),
        # The release surface. Its own router node rather than leaves under
        # `main`: every other node here is a business surface a customer or an
        # operator uses, and this one is the set of acts that change what the
        # others do -- simulation, verification, promotion, rollback. Grouped
        # into business surfaces per maintenance rule 3, not one leaf per route.
        # Stage B. Seven routes, split three ways by prefix: a customer's own
        # inbox and one-tap accept/decline, and the operator's issue, report and
        # outcome. The split *is* the authorization boundary, inherited from the
        # existing /chat wildcards rather than restated per route.
        # Stage C's operator and policy surfaces, under the release router
        # because they are the same question from the other end: what is built,
        # what state is it in, and what does the ladder say about promoting it.
        # Stage D's policy surfaces, under the release router for the same
        # reason Stage C is: these answer "what have we learned, and is it safe to
        # act on", which is the release surface's own question.
        # Stage E. Three admin surfaces: the region table, the personalization
        # and device-care tables, and the view with its pane default. Under the
        # release router for the reason Stages C and D are -- these are all
        # answers to "what is built, and what does it permit".
        _node("kaizen_stage_e",
              "region_catalog", "care_personalization_catalog",
              "relationship_catalog", "relationship_view"),
        _node("kaizen_stage_d",
              "care_gate_report", "care_gate_consult",
              "care_weights_report", "offer_outcomes_report",
              "care_measurement_source"),
        _node("kaizen_stage_c",
              "loyalty_status_catalog", "loyalty_status_preview",
              "agent_copilot_preview"),
        _node("offers",
              "customer_inbox", "customer_offer_detail",
              "customer_offer_accept", "customer_offer_decline",
              "offer_issue", "offer_report", "offer_outcome"),
        _node("kaizen",
              "catalog", "flow_catalog", "flow_simulation", "flow_sweep",
              "blockage_report", "blockage_log",
              "completeness_report", "sweep_status", "sweep_now",
              "shadow_report", "shadow_verification",
              "maturity_levels", "candidate_registry", "candidate_measurement",
              "promotion", "safe_levels", "deployment_ledger", "rollback"),
        _node("audit",
              "efficiency", "enhancements", "audit_catalog", "trail_catalog", "log",
              "logs", "summary", "pipeline_stats", "pipeline_event", "transactions",
              "protobuf_spec",
              "governed_log", "integrity", "actors", "timeline",
              "anomalies", "retention", "export",
              "view", "integrity_gates", "dead_letters", "replay",
              "transactions_query", "transactions_integrity", "transactions_export"),
    ),
    _node(  # services ---------------------------------------------------------
        "services",
        _node("chat_analytics",
              "area_scoring", "sentiment", "insights", "recovery", "topic_ranking",
              "topic_policy", "capabilities"),
        _node("topics",
              "catalog", "search", "suggestion", "theme", "selection", "workspace",
              "intelligence", "coverage"),
        _node("bookings",
              "lifecycle", "normalization", "transitions", "ownership", "assignment_report"),
        _node("policy_scoring",
              "policy_tier", "control_posture", "access_band", "can_access", "decision_reports",
              "composition", "topic_metrics", "posture_adjustment", "tier_escalation",
              "health", "recommendations", "decision_trace", "what_if", "coverage",
              "validation", "ops_catalog"),
        _node("retention",
              "snapshots", "trends", "deltas", "retention_dashboard"),
        _node("retention_snapshot_ops",
              "freshness", "health", "operations_status", "compliance", "posture",
              "automation", "launch_readiness", "go_no_go"),
        _node("loyalty_journey",
              "scenario_catalog", "matching", "journey_plan", "admin_report"),
        _node("activity_tree",
              "grouping", "ranking", "smart_filter", "anomaly_rules", "admin_trees"),
        _node("communication_strategy",
              "override", "policy", "culture", "profile", "mood", "decision_trail"),
        _node("efficiency_audit",
              "component_scoring", "classifications", "enhancement_proposals", "catalog"),
        _node("arrears_payments",
              "interest_policies", "late_fees", "quote", "open", "settle",
              "waive_interest", "waive_fees", "waiver_policy"),
        _node("points_exchange",
              "rate_rules", "rate_multipliers", "campaigns", "quote", "wallet",
              "ledger", "admin_rollup"),
        _node("recovery_playbooks",
              "realtime_context", "playbook_rules", "credit_points", "escalation",
              "policy_guardrail", "orchestrator", "auto_sweep", "catalog"),
        # Stage B. Three kinds, each naming the upstream table it reads rather
        # than declaring a fourth offer catalogue: composing an offer already
        # existed in recovery_playbooks and arrears_payments, and what was
        # missing was the second act -- issuing it, handing it over, and
        # recording what came back.
        _node("recovery_offers",
              "offer_kinds", "statuses", "transitions", "event_kinds",
              "generosity_rules", "explanations",
              "offer_eligibility", "offer_contact_gate",
              "goodwill_preview", "waiver_preview", "priority_preview",
              "expiry", "state_machine", "reference",
              "offer_issue", "offer_accept", "offer_decline",
              "offer_outcome", "offer_expiry_sweep", "follow_ups",
              "offer_inbox", "offer_explanation", "offer_report",
              "validation", "catalog"),
        # Stage A (Trust & Visibility). Four services, one per sub-surface; the
        # aggregator is leaf-level under its own node because its sections are
        # composable individually via the `section=` query parameter.
        _node("customer_360",
              "profile", "interactions", "sentiment", "recovery", "loyalty_journey",
              "communication", "payments", "points", "preferences", "admin_rollup"),
        _node("customer_explain",
              "score_bands", "friction_bands", "phrases", "recovery_narration",
              "next_steps", "loyalty_explanation", "churn_explanation",
              "recovery_explanation", "posture_explanation", "validation",
              "catalog"),
        # Stage C, four modules and four responsibilities, deliberately not
        # merged. Loyalty status is earned and monotone; relationship health is
        # live and may fall; the orchestrator carries state between passes; the
        # copilot composes the other three and re-derives none of them.
        _node("loyalty_status",
              "status_rules", "status_tiers", "status_resolution",
              "experiential_signals", "experiential_ledger", "tier_resolution",
              "investment_bands", "risk_inversion", "investment_band",
              "investment_context", "validation", "catalog"),
        # Stage D, part 2: learned complaint weights -> how we care next.
        # Emphasis, not verdict. The three refusals (severity, tier,
        # auto-escalate) are read from complaint_learning's authority table by
        # the validator rather than restated here, so relaxing one upstream fails
        # in this module until someone decides what it means.
        _node("care_weights",
              "dimensions", "weight_rules", "resolution", "signal_metadata",
              "refused_powers", "async_loader", "validation", "catalog"),
        # Stage D, part 1: the one gate every proactive path asks, plus the
        # structural proof that each declared path's source calls it.
        _node("care_gate",
              "proactive_paths", "consult", "decisions", "coverage",
              "source_scan", "service_critical_purposes", "validation", "catalog"),
        _node("relationship_health",
              "health_bands", "health_signals", "health_overrides",
              "band_resolution", "health_report", "evidence_grading",
              "triage_rollup", "status_invariant", "validation", "catalog"),
        # Stage D, part 3: what the outcomes taught us. Ranks and recommends;
        # never applies, because an engine that retunes its own table from its own
        # outputs makes that table unauditable.
        _node("offer_outcomes",
              "outcome_summary", "ranking", "wilson_bound", "recommendations",
              "generosity_ranking", "scale_buckets", "scale_recommendations",
              "journey_report", "stuck_actions", "care_loop_measurements",
              "validation", "catalog"),
        # Stage E, part 1. The local-hour arithmetic lives in one exported place
        # (`local_hour`) so it cannot be inlined back into UTC by a later
        # refactor -- which is how the Stage D gate stayed wrong for a whole
        # stage with every test green.
        _node("region_windows",
              "regions", "region_resolution", "offsets", "local_hour",
              "local_day_of_week", "local_date", "coverage_window",
              "region_open", "contact_window", "validation", "catalog"),
        # Stage E, parts 2 and 5. Two tables, one file: what a message for a
        # purpose may use, and what a recognised device may do without asking
        # again. The second never widens what a message may say.
        _node("care_personalization",
              "personalization_dimensions", "purpose_limits", "resolution",
              "refusal_reasons", "care_steps", "trust_bands", "trust_band",
              "care_paths", "overreach_invariant", "validation", "catalog"),
        # Stage E, parts 3 and 4. The copilot is the default pane and the raw
        # surfaces are reachable but never first, because an agent who has to go
        # and find the thing does not find it.
        _node("relationship_view",
              "panes", "standing", "pane_resolution", "what_is_true",
              "journey_lines", "offer_outcome_lines", "open_commitments",
              "contact_gate", "view", "render", "validation", "catalog"),
        _node("journey_orchestrator",
              "stages", "transitions", "stage_purpose", "stage_timeboxes",
              "initial_state", "precondition_hash", "transition_resolution",
              "attempt_record", "stage_advance", "next_step", "stuck",
              "cycle_summary", "validation", "catalog"),
        _node("agent_copilot",
              "protected_facts", "fact_detection", "leak_marking",
              "confidence", "opening", "what_is_true", "why", "next_action",
              "offer_lines", "card", "validation", "catalog"),
        _node("preferences",
              "catalog", "consents", "consent_trail", "consent_gate",
              "contact_window", "frequency", "channel_preference", "contact_plan",
              "update", "report"),
        _node("self_service",
              "recovery_status", "points_forecast", "policy_posture",
              "status_dashboard", "visible_actions"),
        # Complaints. One leaf per decision-support surface rather than per
        # config table, so the tree says what an operator can ask for.
        _node("complaints",
              "case_lifecycle", "case_timeline", "case_ownership",
              "escalation_triggers", "escalation_guards", "escalation_decision",
              "authority_floor", "routing", "sla_matrix", "regulatory_deadline",
              "decision_feeds", "decision_dossier", "precedent_retrieval",
              "decision_history", "auto_escalation_sweep", "sla_report",
              "admin_rollup", "case_linkage", "validation", "catalog",
              # The eleventh dossier feed, contributed by complaint_learning
              # rather than by this module. Declared here because a feed is a
              # property of the dossier it appears in, and leaving it undeclared
              # would make the feed list and the context keys disagree.
              "loyalty_contribution_feed"),
        # Complaint learning. Its own service node because it is a different
        # mechanism from `complaints` -- a detector that opens cases, a learner
        # that reweights signals, and a clusterer that proposes work -- and
        # folding it into the complaints node would hide that the authority
        # boundary between them is the design.
        _node("complaint_learning",
              "loyalty_objective", "loyalty_signals", "learning_parameters",
              "weight_authority", "signal_readers", "contribution_scoring",
              "weight_update", "confidence", "weight_report",
              "loyalty_facts", "learning_pass", "weight_store",
              "system_detectors", "detector_gates", "system_raise",
              "system_raised_listing", "cluster_detection", "cluster_thresholds",
              "proposal_rendering", "proposal_store", "proposal_publishing",
              "blockages_render", "validation", "catalog"),
        _node("audit_log",
              "record", "list", "summary", "action_catalog",
              "governed_record", "action_aliases", "action_specs",
              "severity_policy", "justification", "sensitive_detail",
              "redaction", "change_detail", "paging", "count",
              "retention_plan", "retention_advice", "actor_activity",
              "entity_timeline", "anomaly_detection", "seal_chain",
              "chain_verification", "trail_export",
              "view_profiles", "integrity_gates", "entry_seal_chain", "catalog"),
        # Sign-in. Three service nodes because they fail independently and are
        # governed separately: which credentials exist, how much proof a login
        # is asked for, and what a customer may connect.
        #
        # `refused_patterns` is a leaf rather than an omission on purpose. The
        # methods this service declines to offer are a decision, and a decision
        # that exists only as an absence cannot be reviewed, published, or
        # argued with.
        _node("auth_methods",
              "method_table", "refused_patterns", "one_time_codes",
              "trusted_device_credentials", "validation", "catalog"),
        # `credential_vocabulary` and `demand_resolution` are the two leaves
        # that keep recognition from becoming authentication: the first is
        # closed and validated, the second refuses to demand a credential an
        # account cannot produce.
        _node("device_recognition",
              "signal_scoring", "policy_bands", "credential_vocabulary",
              "demand_resolution", "enforcement_modes", "digesting",
              "validation", "catalog"),
        # `scope_ladders` carries the consequence of each scope, including that
        # the broadest one grants deletion -- the reason the broad end needs an
        # explicit confirmation rather than being the default.
        _node("storage_providers",
              "provider_registry", "scope_ladders", "pkce", "token_exchange",
              "token_encryption", "connection_health", "revocation",
              "validation", "catalog"),
        # Mail. `delivery_boundary` is the leaf that matters: three transports
        # behind one interface, and the split between *accepted* and *delivered*
        # that stops an unconfigured deployment from claiming a code is on its
        # way when nothing was sent.
        _node("mail",
              "delivery_boundary", "transport_registry", "otp_message",
              "simulated_outbox", "validation", "catalog"),
    ),
    _node(  # schemas ----------------------------------------------------------
        "schemas",
        _node("schemas_core",
              "user", "token", "booking", "policy_score", "topic_selection",
              "session_lifecycle", "machine_credentials", "password_feedback",
              "security_posture", "step_up",
              # Sign-in contract families. `recognition_verdict` is its own leaf
              # because of what it must not carry: contributions, never the raw
              # signals behind them, and nothing that reads as a grant.
              "auth_method", "recognition_verdict", "otp",
              "trusted_device", "identity", "storage"),
        _node("schemas_chat",
              "insight", "recovery", "recovery_playbooks", "retention", "snapshot_ops", "topic_ranking", "topic_policy",
              # Stage A contract families, one leaf per payload family.
              "customer_360", "customer_explanations", "customer_recovery",
              "preference_consent", "self_service",
              # Complaints contract family.
              "complaint_case", "complaint_event", "complaint_decision",
              "complaint_dossier", "complaint_precedent",
              "complaint_decision_support", "complaint_admin", "complaint_catalog"),
        _node("schemas_audit",
              "efficiency", "enhancements", "audit_trail",
              "governed_write", "integrity", "actors", "timeline",
              "anomalies", "retention", "export",
              "view_projection", "integrity_gates", "dead_letters", "replay",
              "transaction_query", "transaction_integrity", "transaction_export",
              # Contract-governance layer over the 40 shipped models. The
              # contracts above are unchanged; these are the tables, the
              # readers and the reports.
              "kinds", "audiences", "field_policies", "trivial_fields",
              "forbidden_fields", "inventory", "write_paths", "contract_ops",
              "findings_taxonomy",
              "model_scan", "field_facts", "source_scan", "field_resolution",
              "route_map", "kind_inference",
              "contract_inventory", "field_description", "divergence_report",
              "redaction_report", "contract_validation", "governance_catalog"),
    ),
)


# ---------------------------------------------------------------------------
# Serialization + validation
# ---------------------------------------------------------------------------


def serialize(node) -> str:
    if isinstance(node, str):
        return node
    label = node[0]
    children = node[1:]
    return "(" + ",".join(serialize(child) for child in children) + ")" + label


class _Parser:
    def __init__(self, text: str):
        self.text = text
        self.pos = 0
        self.leaves = 0
        self.internal = 0

    def _label(self):
        start = self.pos
        while self.pos < len(self.text) and self.text[self.pos] not in "(),;":
            self.pos += 1
        return self.text[start:self.pos]

    def parse(self):
        self._skip_ws()
        if self.pos >= len(self.text) or self.text[self.pos] != "(":
            raise ValueError("tree must start with '('")
        self.node()
        self._skip_ws()
        if self.text[self.pos : self.pos + 1] != ";":
            raise ValueError("tree must end with ';'")

    def _skip_ws(self):
        while self.pos < len(self.text) and self.text[self.pos].isspace():
            self.pos += 1

    def node(self):
        assert self.text[self.pos] == "("
        self.pos += 1
        self._skip_ws()
        while True:
            if self.text[self.pos] == "(":
                self.node()
            else:
                label = self._label()
                if not label:
                    raise ValueError(f"empty leaf at offset {self.pos}")
                self.leaves += 1
            self._skip_ws()
            if self.text[self.pos] == ",":
                self.pos += 1
                self._skip_ws()
                continue
            if self.text[self.pos] == ")":
                self.pos += 1
                self._skip_ws()
                label = self._label()
                if not label:
                    raise ValueError("internal node missing label")
                self.internal += 1
                return
            raise ValueError(f"unexpected char {self.text[self.pos]!r} at offset {self.pos}")


def parse_and_count(text: str) -> tuple[int, int]:
    parser = _Parser(text)
    parser.parse()
    return parser.leaves, parser.internal


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="validate without writing")
    args = ap.parse_args()

    tree = serialize(TREE) + ";"
    leaves, internal = parse_and_count(tree)
    lines = HEADER + tree + "\n"
    print(f"leaves={leaves} internal_nodes={internal}")
    if args.check:
        return 0
    OUTPUT.write_text(lines, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())